---
title: "Tweets from the first Presidential Debate"
output:
  html_document: 
    number_sections: yes
    theme: journal
  html_notebook:
    code_folding: hide
    theme: journal
editor_options:
  chunk_output_type: console
---


```{r}
library(readxl)
library(plyr)
```

# Before the debate

```{r}
before <- read_xlsx("C:/Users/jm/Documents/sawi/5000 samples/all.xlsx", sheet = "before")

table(before$tweet_type)
```

```{r include=FALSE}
count(before$in_reply_to_user_id)
count(before$retweet_or_quote_user_id)

summary(before[,c(7,11,17:19,21, 23)])
```

# During - sample A
```{r}
during_a <- read_xlsx("C:/Users/jm/Documents/sawi/5000 samples/all.xlsx", sheet = "during a")
table(during_a$tweet_type)
summary(during_a[,c(7,11,17:19,21, 23)])

```

# During - sample B
```{r}
during_b <- read_xlsx("C:/Users/jm/Documents/sawi/5000 samples/all.xlsx", sheet = "during b")
table(during_b$tweet_type)
summary(during_b[,c(7,11,17:19,21,23)])
```

# During - sample C
```{r}
during_c <- read_xlsx("C:/Users/jm/Documents/sawi/5000 samples/all.xlsx", sheet = "during c")
table(during_c$tweet_type)
summary(during_c[,c(7,11,17:19,21, 23)])
```

# After the debate
```{r}
after <- read_xlsx("C:/Users/jm/Documents/sawi/5000 samples/all.xlsx", sheet = "after")
table(after$tweet_type)
summary(after[,c(7,11,17:19,21, 23)])

```
